#Tomcat Embedded Server Configuration
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      routes:
        - id: ms-medicamento
          uri: http://localhost:8001/
          predicates:
            - Path=/apiM/**
        - id: ms-venta
          uri: http://localhost:8002/
          predicates:
            - Path=/apiV/**
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

